[package]
name = "resc"
version = "0.1.1"
authors = ["Denys Séguret <denys.seguret@gmail.com>"]

[dependencies]
lazy_static = "1.1.0"
redis = "0.9.1"
regex = "1.0.5"
serde_json = "1.0"
reqwest = "0.9.2"
log = "0.4"
env_logger = "0.5.13"
