[package]
name = "resc"
version = "0.2.0"
authors = ["Denys Séguret <denys.seguret@gmail.com>"]
edition = "2018"
description = "A Redis based task orchestrator"
license = "MIT"

[dependencies]
lazy_static = "1.4"
redis = "0.17"
regex = "1.3"
serde_json = "1.0"
reqwest = "0.9"
log = "0.4"
env_logger = "0.5.13"
chrono = "0.4"
